# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2270e82160e84a2cd23b875d04a368ed1536b663adeb7e92ed7456e19dd0c6e6f68f5a34a15b85b6b3fc30c7201ee3fef9b68c488034d955d6015f1d9eea08e

test:
  secret_key_base: dce291ba4a702a3817dc4bce474396e01232aa13d4a082eed696e36101b22232dc96b178a92cbcd3e56a76d8b6e23b6dd668370c0f90c468f7344692b7f95ab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
